---

- name: Update apt cache if needed
  apt: update_cache=yes cache_valid_time=3600
  become: true

- name: Install ruby-build dependencies
  apt: pkg={{ item }} state=present
  become: true
  with_items:
  - git
  - autoconf
  - bison
  - build-essential
  - libssl-dev
  - libyaml-dev
  - libreadline6-dev
  - zlib1g-dev
  - libncurses5-dev
  - libffi-dev
  - libgdbm3
  - libgdbm-dev